# Generated by Django 5.2.13 on 2026-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0001_initial_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsnapshot',
            name='demand_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='growth_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='staleness_index',
            field=models.IntegerField(default=0),
        ),
    ]
