# Generated by Django 5.2.13 on 2026-04-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('years_experience', models.FloatField(blank=True, null=True)),
                ('freshness_score', models.IntegerField()),
                ('decay_reason', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='core_engine.userprofile')),
            ],
            options={
                'ordering': ['-analyzed_at', '-freshness_score'],
            },
        ),
    ]
