# Generated by Django 5.2.13 on 2026-04-10 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0002_add_staleness_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('jd_text', models.TextField(blank=True)),
                ('path_preference', models.CharField(choices=[('hacker', 'Hacker Path'), ('certified', 'Certified Path'), ('both', 'Both Paths')], default='both', max_length=20)),
                ('overall_gap_score', models.IntegerField(default=0)),
                ('overlap_pct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('gap_severity', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('bridge_hint', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('hacker_resources', models.JSONField(default=list)),
                ('certified_resources', models.JSONField(default=list)),
                ('capstone_task', models.JSONField(blank=True, default=dict)),
                ('proof_of_work', models.TextField(blank=True)),
                ('review_result', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core_engine.roadmapprogress')),
            ],
            options={
                'ordering': ['gap_severity', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('verified', 'Verified')], default='claimed', max_length=20)),
                ('years_experience', models.FloatField(blank=True, null=True)),
                ('freshness_score', models.IntegerField(default=50)),
                ('staleness_index', models.IntegerField(default=50)),
                ('demand_score', models.IntegerField(default=50)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('staleness_breakdown', models.JSONField(default=dict)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_map', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-freshness_score'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_engine_user_id_e96b2c_idx'), models.Index(fields=['user', 'freshness_score'], name='core_engine_user_id_400078_idx')],
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
