# Generated by Django 6.0.4 on 2026-04-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0003_skilltest_testattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('udemy', 'Udemy')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('channel', models.CharField(blank=True, default='', max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core_engine.skill')),
            ],
            options={
                'ordering': ['source', 'title'],
                'unique_together': {('skill', 'url')},
            },
        ),
    ]
