# Generated by Django 5.2.13 on 2026-04-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0003_gapreport_skillgap'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('hacker', 'Hacker Path'), ('certified', 'Certified Path')], max_length=20)),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gap_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='core_engine.gapreport')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='core_engine.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('step_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('resource_url', models.URLField(blank=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('project', 'Project'), ('course', 'Course'), ('cert', 'Certification'), ('docs', 'Documentation')], default='article', max_length=20)),
                ('estimated_hours', models.FloatField(default=0)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core_engine.learningpath')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
    ]
