# Generated by Django 5.2.13 on 2026-04-11 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0003_add_skillmap_roadmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('trending', models.BooleanField(default=False)),
                ('task', models.TextField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('resources', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_weeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week'],
                'unique_together': {('user', 'week')},
            },
        ),
    ]
