# Generated by Django 6.0.4 on 2026-04-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0005_portfolio_portfolioskillentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'ordering': ['-started_at']},
        ),
    ]
