# Generated by Django 6.0.4 on 2026-04-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine', '0006_alter_skill_options_alter_skillcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillbadge',
            options={'ordering': ['-awarded_at']},
        ),
    ]
