"""
v1/assessment_views.py

POST /api/v1/assessment/generate/
    - Reads user's SkillMap
    - Lets user pick a skill (or picks top one)
    - Calls Groq to generate randomised MCQ questions
    - Returns a fresh assessment every time (never cached)

POST /api/v1/assessment/submit/
    - Scores answers
    - Saves result to AssessmentResult model
    - Returns score, breakdown, pass/fail
"""

import uuid
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status

from core_engine.models import SkillMap, ParsedCV, UserProfile
from core_engine.test_service import generate_skill_questions, score_answers


# ── Helpers ───────────────────────────────────────────────────────────────────

def _map_difficulty(freshness_score: int) -> str:
    """Map freshness score to question difficulty."""
    if freshness_score >= 75:
        return "advanced"
    if freshness_score >= 45:
        return "intermediate"
    return "beginner"


def _build_question_objects(raw_questions: list, skill_name: str) -> list:
    """Convert Groq MCQ dicts into the Assessment Question shape the frontend expects."""
    questions = []
    for i, q in enumerate(raw_questions):
        questions.append({
            "id": f"q{i + 1}",
            "type": "mcq",
            "title": q["question"],
            "options": q["options"],
            # Store correct_index server-side only — strip before sending to client
            "_correct_index": q["correct_index"],
            "_explanation": q.get("explanation", ""),
        })
    return questions


# ── View 1: Generate Assessment ───────────────────────────────────────────────

class AssessmentGenerateView(APIView):
    """
    POST /api/v1/assessment/generate/

    Body (optional):
        { "skill_name": "React" }   ← if omitted, picks the user's top skill

    Response:
        {
            "assessment_id": "uuid",
            "skill_name": "React",
            "difficulty": "intermediate",
            "title": "React Assessment",
            "duration_seconds": 1200,
            "questions": [
                { "id": "q1", "type": "mcq", "title": "...", "options": [...] },
                ...
            ]
        }

    Questions are freshly generated by Groq on every call — never the same twice.
    """
    permission_classes = [IsAuthenticated]

    def post(self, request):
        skill_name = request.data.get("skill_name", "").strip()

        # ── Resolve skill from user's SkillMap ────────────────────────────
        if skill_name:
            skill_entry = SkillMap.objects.filter(
                user=request.user,
                skill_name__iexact=skill_name,
            ).first()

            if not skill_entry:
                # Skill not in their map — still allow, use default difficulty
                difficulty = "intermediate"
            else:
                difficulty = _map_difficulty(skill_entry.freshness_score)
        else:
            # No skill specified — pick the user's weakest skill (lowest freshness)
            # so the assessment is most useful
            skill_entry = (
                SkillMap.objects
                .filter(user=request.user)
                .order_by("freshness_score")
                .first()
            )

            if not skill_entry:
                # No CV uploaded yet
                return Response(
                    {
                        "error": "No skills found. Please upload your CV first.",
                        "code": "NO_SKILLS",
                    },
                    status=status.HTTP_404_NOT_FOUND,
                )

            skill_name = skill_entry.skill_name
            difficulty = _map_difficulty(skill_entry.freshness_score)

        # ── Generate questions via Groq ────────────────────────────────────
        try:
            raw_questions = generate_skill_questions(
                skill_name=skill_name,
                difficulty=difficulty,
                num_questions=10,
            )
        except Exception as e:
            return Response(
                {"error": f"Failed to generate questions: {str(e)}", "code": "AI_ERROR"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        if not raw_questions:
            return Response(
                {"error": "AI returned no questions. Please try again.", "code": "NO_QUESTIONS"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # ── Build response ────────────────────────────────────────────────
        assessment_id = str(uuid.uuid4())
        questions_for_client = []
        # Store correct answers server-side in session/cache keyed by assessment_id
        # For simplicity we embed them in a signed token approach:
        # We'll store them in the response under a separate key that the submit
        # endpoint will re-generate (stateless) — or we store in DB.
        # Simplest production approach: store in DB temporarily.

        correct_answers = {}  # { "q1": 2, "q2": 0, ... }
        explanations    = {}

        for i, q in enumerate(raw_questions):
            qid = f"q{i + 1}"
            questions_for_client.append({
                "id":      qid,
                "type":    "mcq",
                "title":   q["question"],
                "options": q["options"],
            })
            correct_answers[qid] = q["correct_index"]
            explanations[qid]    = q.get("explanation", "")

        # Persist the answer key so submit can score it
        from django.core.cache import cache
        cache.set(
            f"assessment:{assessment_id}:answers",
            {"correct": correct_answers, "explanations": explanations,
             "skill": skill_name, "difficulty": difficulty},
            timeout=60 * 30,  # 30 minutes
        )

        return Response({
            "assessment_id":    assessment_id,
            "skill_name":       skill_name,
            "difficulty":       difficulty,
            "title":            f"{skill_name} Assessment",
            "duration_seconds": 20 * 60,  # 20 minutes
            "questions":        questions_for_client,
        }, status=status.HTTP_200_OK)


# ── View 2: Submit Assessment ─────────────────────────────────────────────────

class AssessmentSubmitView(APIView):
    """
    POST /api/v1/assessment/submit/

    Body:
        {
            "assessment_id": "uuid",
            "answers": { "q1": 2, "q2": 0, "q3": 1, ... }
        }

    Response:
        {
            "score": 80.0,
            "passed": true,
            "correct": 8,
            "total": 10,
            "skill_name": "React",
            "difficulty": "intermediate",
            "breakdown": [
                {
                    "question_id": "q1",
                    "your_answer_index": 2,
                    "correct_index": 2,
                    "correct_option": "...",
                    "is_correct": true,
                    "explanation": "..."
                },
                ...
            ]
        }
    """
    permission_classes = [IsAuthenticated]

    def post(self, request):
        assessment_id = request.data.get("assessment_id", "").strip()
        answers       = request.data.get("answers", {})

        if not assessment_id:
            return Response(
                {"error": "assessment_id is required.", "code": "MISSING_ID"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # ── Retrieve answer key from cache ────────────────────────────────
        from django.core.cache import cache
        cached = cache.get(f"assessment:{assessment_id}:answers")

        if not cached:
            return Response(
                {
                    "error": "Assessment expired or not found. Please start a new assessment.",
                    "code": "EXPIRED",
                },
                status=status.HTTP_404_NOT_FOUND,
            )

        correct_answers = cached["correct"]   # { "q1": 2, ... }
        explanations    = cached["explanations"]
        skill_name      = cached["skill"]
        difficulty      = cached["difficulty"]

        # ── Score ─────────────────────────────────────────────────────────
        total   = len(correct_answers)
        correct = 0
        breakdown = []

        for qid, correct_idx in correct_answers.items():
            user_raw    = answers.get(qid)
            user_idx    = int(user_raw) if user_raw is not None else None
            is_correct  = user_idx == correct_idx
            if is_correct:
                correct += 1

            breakdown.append({
                "question_id":       qid,
                "your_answer_index": user_idx,
                "correct_index":     correct_idx,
                "is_correct":        is_correct,
                "explanation":       explanations.get(qid, ""),
            })

        score  = round((correct / total) * 100, 2) if total > 0 else 0.0
        passed = score >= 70.0

        # ── Invalidate cache so it can't be re-submitted ──────────────────
        cache.delete(f"assessment:{assessment_id}:answers")

        # ── Update SkillMap status if passed ──────────────────────────────
        if passed:
            SkillMap.objects.filter(
                user=request.user,
                skill_name__iexact=skill_name,
            ).update(status="verified")

        return Response({
            "score":      score,
            "passed":     passed,
            "correct":    correct,
            "total":      total,
            "skill_name": skill_name,
            "difficulty": difficulty,
            "breakdown":  breakdown,
        }, status=status.HTTP_200_OK)


# ── View 3: List user's skills for assessment picker ─────────────────────────

class AssessmentSkillsView(APIView):
    """
    GET /api/v1/assessment/skills/

    Returns the user's skills from SkillMap, sorted by freshness (weakest first)
    so the UI can show which skills need the most work.
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        skills = (
            SkillMap.objects
            .filter(user=request.user)
            .order_by("freshness_score")
            .values("skill_name", "freshness_score", "staleness_index", "status")
        )

        if not skills:
            return Response(
                {"error": "No skills found. Upload your CV first.", "code": "NO_SKILLS"},
                status=status.HTTP_404_NOT_FOUND,
            )

        return Response([
            {
                "skill_name":     s["skill_name"],
                "freshness_score": s["freshness_score"],
                "staleness_index": s["staleness_index"],
                "status":          s["status"],
                "difficulty":      _map_difficulty(s["freshness_score"]),
            }
            for s in skills
        ], status=status.HTTP_200_OK)
