"""
portfolio_service.py
Handles portfolio generation and PDF export.
"""
from django.utils.text import slugify
from django.utils import timezone


def generate_portfolio(user):
    """
    Builds or rebuilds the user's portfolio from all verified UserSkills.
    Returns the Portfolio instance.
    """
    from .models import Portfolio, PortfolioSkillEntry, UserSkill, SkillBadge, LearningResource

    # Build a unique slug from username
    base_slug = slugify(user.username)
    slug      = base_slug
    counter   = 1
    while Portfolio.objects.filter(slug=slug).exclude(user=user).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1

    # Safely get bio from profile
    try:
        bio = user.profile.bio or ""
    except Exception:
        bio = ""

    # Get or create portfolio — updated_at is auto_now so we don't set it manually
    portfolio, _ = Portfolio.objects.update_or_create(
        user=user,
        defaults={
            "slug":         slug,
            "bio_snapshot": bio,
        },
    )

    # Get all verified skills for this user
    verified_skills = UserSkill.objects.filter(
        user=user, status="verified"
    ).select_related("skill")

    # Clear old entries and rebuild
    PortfolioSkillEntry.objects.filter(portfolio=portfolio).delete()

    for user_skill in verified_skills:
        skill = user_skill.skill

        # Get badge if exists
        badge = SkillBadge.objects.filter(user=user, skill=skill).first()

        # Get top 3 resources for this skill
        resources = list(LearningResource.objects.filter(skill=skill)[:3])

        entry = PortfolioSkillEntry.objects.create(
            portfolio=portfolio,
            skill=skill,
            badge=badge,
            score=user_skill.score or 0,
        )
        if resources:
            entry.resources.set(resources)

    return portfolio


def generate_portfolio_pdf(portfolio):
    """
    Generates a PDF from the portfolio data using WeasyPrint.
    Returns PDF bytes.
    """
    import weasyprint

    skill_rows = ""
    for entry in portfolio.skill_entries.select_related("skill", "badge").all():
        badge_info  = f"Verified — Score: {entry.score}%" if entry.badge else f"Score: {entry.score}%"
        badge_id    = str(entry.badge.verification_hash)[:8] + "..." if entry.badge else "—"
        skill_rows += f"""
        <tr>
            <td>{entry.skill.name}</td>
            <td>{entry.skill.get_difficulty_display()}</td>
            <td>{badge_info}</td>
            <td>{badge_id}</td>
        </tr>
        """

    bio_html      = f"<p><strong>Bio:</strong> {portfolio.bio_snapshot}</p>" if portfolio.bio_snapshot else ""
    generated_on  = portfolio.updated_at.strftime("%B %d, %Y")
    empty_row     = "<tr><td colspan='4'>No verified skills yet.</td></tr>"

    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body     {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
        h1       {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2       {{ color: #3498db; margin-top: 30px; }}
        table    {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th       {{ background: #3498db; color: white; padding: 10px; text-align: left; }}
        td       {{ padding: 10px; border-bottom: 1px solid #ddd; }}
        .footer  {{ margin-top: 40px; font-size: 12px; color: #999; text-align: center; }}
    </style>
</head>
<body>
    <h1>SkillBridge Verified Portfolio</h1>
    <h2>{portfolio.user.get_full_name() or portfolio.user.username}</h2>
    <p><strong>Username:</strong> {portfolio.user.username}</p>
    <p><strong>Profile:</strong> skillbridge.app/portfolio/{portfolio.slug}</p>
    {bio_html}
    <p><strong>Generated:</strong> {generated_on}</p>
    <h2>Verified Skills</h2>
    <table>
        <thead>
            <tr><th>Skill</th><th>Level</th><th>Status</th><th>Badge ID</th></tr>
        </thead>
        <tbody>
            {skill_rows if skill_rows else empty_row}
        </tbody>
    </table>
    <div class="footer">Generated by SkillBridge &middot; Verified credentials powered by AI</div>
</body>
</html>"""

    return weasyprint.HTML(string=html_content).write_pdf()
